name: 'Maven Tests (JUnit)'

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  build:
    name: pull request on main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
        # set batchmode so maven shut-up
      - run: echo "--batch-mode" >> .mvn/maven.config
      - name: Set Up
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Deploy
        run: mvn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
