name: 'Maven Tests (JUnit)'

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  build:
    name: 'pull request on main'
    runs-on: ubuntu-latest

    steps:
      - name: 'Load Repository'
        uses: actions/checkout@v4
      
      - name: 'Have Maven Shut Up'
        run: echo "--batch-mode" >> .mvn/maven.config
      
      - name: 'Setup Java & Maven'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: 'Run Tests'
        run: mvn test
