on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  build:
    name: pull request on main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: mvn clean install

      # https://docs.github.com/fr/actions/use-cases-and-examples/publishing-packages/publishing-java-packages-with-maven
      - name: Deploy
        # if: success()
        # github.ref == 'refs/heads/main' : Vérifit et assure que ca dépoit uniquement après la fusion de la PR avec la branche main
       # if: github.ref == 'refs/heads/main' && success()
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
