name: 'On Main Release'

description: 'Put a release out & Update version'

on:
  push: 
    branches:
      - 'main'
    paths-ignore:
      - 'version_value'

jobs:
  build:
    name: 'Actual Stuff'
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - name: 'Load Repository'
        uses: actions/checkout@v4

      - name: 'Have Maven Shut Up'
        run: echo "--batch-mode" >> .mvn/maven.config
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                        https://maven.apache.org/xsd/settings-1.0.0.xsd">
              <servers>
                  <server>
                      <id>github</id>  <!-- Must match distributionManagement in pom.xml -->
                      <username>\${env.GITHUB_ACTOR}</username>
                      <password>\${env.GITHUB_TOKEN}</password>
                  </server>
              </servers>
          </settings>
          EOF
      
      - name: 'Setup Java & Maven'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github

      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: 'Update version'
        run: |
          python3 version_handler.py min

      - name: 'Packge all the stuff'
        run: |
          mvn versions:set -DnewVersion=$(cat version_value)
          rm -f pom.xml.versionsBackup
          mvn package

      - name: 'Make release'
        run: gh release create $(cat version_value) --generate-notes ./target/*.jar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


        
      - name: Publish to GitHub Packages
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  


      - name: 'Add Version & Commit'
        run: |
          git add version_value
          git commit -m "put release $(cat version_value)"

      - name: 'Push To Main'
        run: git push


      - name: Merge staging -> dev
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
